const dummyNotes: Note[] = [
	{
		id: '1',
		title: 'Meeting with Team',
		description: 'Discuss project updates and plan for next sprint.',
		label: 'Work',
		date: new Date(),
		time: '10:00 AM',
		color: '#FF9800',
		completed: false,
		priority: 'high',
		attachments: [],
		reminders: [],
	},
	{
		id: '2',
		title: 'Buy Groceries',
		description: 'Milk, eggs, bread, and fruits.',
		label: 'Shopping',
		date: new Date(),
		time: '04:00 PM',
		color: '#2196F3',
		completed: false,
		priority: 'medium',
		attachments: [],
		reminders: [],
	},
	{
		id: '3',
		title: 'Gym Workout',
		description: 'Leg day: squats, lunges, and leg press.',
		label: 'Health',
		date: new Date(),
		time: '06:30 AM',
		color: '#4CAF50',
		completed: true,
		priority: 'low',
		attachments: [],
		reminders: [],
	},
];
